#!/usr/bin/env python3
"""Streamlit UI for the movie recommender.

    streamlit run app.py
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import streamlit as st

from src.collaborative import ItemItemCF, SVDRecommender
from src.content_based import ContentBasedRecommender, TitleNotFoundError
from src.data_loader import load_data, split_field
from src.hybrid import HybridRecommender

st.set_page_config(page_title="Movie Recommender", page_icon="🎬", layout="wide")

CARD_CSS = """
<style>
.card {border:1px solid rgba(140,140,160,.28); border-radius:12px; padding:14px 16px; margin-bottom:12px;
       background:rgba(140,140,160,.06);}
.card h4 {margin:0 0 6px 0; font-size:1.05rem;}
.badge {display:inline-block; padding:2px 8px; margin:0 6px 6px 0; border-radius:999px;
        font-size:.74rem; background:rgba(90,130,255,.18); border:1px solid rgba(90,130,255,.35);}
.meta {font-size:.82rem; opacity:.78; margin-bottom:6px;}
.why {font-size:.84rem; opacity:.92; border-left:3px solid rgba(90,130,255,.6); padding-left:9px; margin-top:8px;}
.scorebar {height:6px; border-radius:4px; background:rgba(90,130,255,.75); margin-top:8px;}
</style>
"""


@st.cache_resource(show_spinner="Loading data and fitting models…")
def load_models():
    data = load_data()
    content = ContentBasedRecommender(data.movies)
    item_cf = ItemItemCF().fit(data.ratings, data.movies["movie_id"])
    svd = SVDRecommender().fit(data.ratings, data.movies["movie_id"])
    hybrid = HybridRecommender(data=data, content=content, item_cf=item_cf, svd=svd)
    return data, content, item_cf, svd, hybrid


def movie_card(row: pd.Series, score: float, score_label: str, why: str | None, fill: float = 1.0) -> str:
    genres = "".join(f"<span class='badge'>{g}</span>" for g in split_field(row["genres"]))
    width = int(max(3, min(100, fill * 100)))
    cast = ", ".join(split_field(row.get("cast"))[:3])
    parts = [
        "<div class='card'>",
        f"<h4>{row['title']} <span style='opacity:.6;font-weight:400'>({int(row['year'])})</span></h4>",
        f"<div class='meta'>dir. {row['director']} · {int(row['runtime'])} min · ⭐ {row['vote_average']:.1f}"
        f" · {score_label} <b>{score:.3f}</b></div>",
        f"<div>{genres}</div>",
        f"<div class='meta'>{cast}</div>",
        f"<div class='meta'>{row['overview']}</div>",
        f"<div class='scorebar' style='width:{width}%'></div>",
    ]
    if why:
        parts.append(f"<div class='why'><b>Why this?</b> {why}</div>")
    parts.append("</div>")
    return "".join(parts)


def render_cards(frame: pd.DataFrame, movies: pd.DataFrame, score_col: str, score_label: str, whys: dict[int, str], columns: int = 2) -> None:
    cols = st.columns(columns)
    lookup = movies.set_index("movie_id")
    scores = frame[score_col].to_numpy(dtype=float)
    hi = float(np.max(scores)) if len(scores) else 1.0
    lo = min(0.0, float(np.min(scores))) if len(scores) else 0.0
    for i, (_, rec) in enumerate(frame.iterrows()):
        movie_id = int(rec["movie_id"])
        row = lookup.loc[movie_id]
        row = pd.Series({**row.to_dict(), "movie_id": movie_id})
        with cols[i % columns]:
            value = float(rec[score_col])
            fill = (value - lo) / (hi - lo) if hi > lo else 1.0
            st.markdown(
                movie_card(row, value, score_label, whys.get(movie_id), fill=fill),
                unsafe_allow_html=True,
            )


def main() -> None:
    st.markdown(CARD_CSS, unsafe_allow_html=True)
    data, content, item_cf, svd, hybrid = load_models()
    titles = data.movies["title"].tolist()

    st.title("🎬 Movie Recommender")
    st.caption(
        f"{len(data.movies)} movies · {data.n_users} users · {data.n_ratings:,} synthetic ratings "
        "(generated by `data/generate_ratings.py` — not real user data)"
    )

    with st.sidebar:
        st.header("Settings")
        method = st.radio(
            "Method",
            ["hybrid", "content", "cf", "svd", "popularity"],
            format_func={
                "hybrid": "Hybrid (content + collaborative)",
                "content": "Content-based (TF-IDF)",
                "cf": "Item-item collaborative filtering",
                "svd": "Matrix factorisation (SVD)",
                "popularity": "Popularity (IMDb weighted rating)",
            }.get,
        )
        n = st.slider("How many recommendations", 3, 24, 8)
        alpha = st.slider(
            "α — content ⟷ collaborative", 0.0, 1.0, 0.5, 0.05,
            help="1.0 = purely content based, 0.0 = purely collaborative",
            disabled=method != "hybrid",
        )
        st.divider()
        use_title = st.checkbox("Seed with a movie", value=True)
        title = st.selectbox("Movie", titles, index=titles.index("Inception") if "Inception" in titles else 0,
                             disabled=not use_title)
        free_text = st.text_input("…or type a title (fuzzy matched)", "", disabled=not use_title)
        use_user = st.checkbox("Personalise for a user", value=False)
        user_ids = sorted(data.ratings["user_id"].unique().tolist())
        user_id = st.selectbox("User id", user_ids, index=min(41, len(user_ids) - 1), disabled=not use_user)
        show_why = st.checkbox("Show 'why this?' explanations", value=True)

    seed_title: str | None = None
    if use_title:
        seed_title = free_text.strip() or title
    active_user = int(user_id) if use_user else None

    if seed_title:
        try:
            idx = content.resolve_title(seed_title)
            matched = content.title_of_index(idx)
            if matched.lower() != seed_title.lower():
                st.info(f"Matched **{matched}** for “{seed_title}”.")
            seed_title = matched
        except TitleNotFoundError as exc:
            st.error(str(exc))
            st.stop()

    if active_user is not None:
        profile = hybrid.user_profile(active_user)
        with st.expander(f"User {active_user}: {len(profile)} ratings (mean {profile['rating'].mean():.2f})"):
            top = profile.head(10).merge(data.movies[["movie_id", "title", "year", "genres"]], on="movie_id")
            st.dataframe(top[["title", "year", "genres", "rating"]], hide_index=True, width="stretch")

    # ------------------------------------------------------------ dispatch
    whys: dict[int, str] = {}
    if method == "content":
        if not seed_title:
            st.warning("Content-based recommendations need a seed movie — tick “Seed with a movie”.")
            st.stop()
        frame = content.recommend(seed_title, n=n)
        score_col, score_label = "score", "cosine"
        seed_id = data.id_of(seed_title)
        if show_why:
            whys = {int(m): content.explain_text(seed_id, int(m)) for m in frame["movie_id"]}
        header = f"Because you picked **{seed_title}**"

    elif method in ("cf", "svd"):
        if active_user is None:
            st.warning("Collaborative methods need a user — tick “Personalise for a user”.")
            st.stop()
        model = item_cf if method == "cf" else svd
        frame = model.recommend(active_user, n=n)
        score_col, score_label = "score", "predicted ★"
        if show_why:
            whys = {int(m): hybrid.explain(int(m), user_id=active_user) for m in frame["movie_id"]}
        header = f"Top picks for **user {active_user}** ({'item-item CF' if method == 'cf' else f'SVD, k={svd.n_components_}'})"

    elif method == "popularity":
        pop = hybrid.popularity_scores()
        order = np.argsort(-pop)[:n]
        frame = pd.DataFrame({"movie_id": hybrid.movie_ids[order], "score": pop[order]})
        score_col, score_label = "score", "weighted rating"
        if show_why:
            whys = {int(m): hybrid.explain(int(m)) for m in frame["movie_id"]}
        header = "Most popular in the catalogue (IMDb weighted rating)"

    else:  # hybrid
        frame = hybrid.recommend(user_id=active_user, title=seed_title, n=n, alpha=alpha)
        score_col, score_label = "score", "blend"
        if show_why:
            whys = {int(m): hybrid.explain(int(m), user_id=active_user, title=seed_title) for m in frame["movie_id"]}
        header = f"Hybrid recommendations · `{frame.attrs['method']}`"

    st.subheader(header)
    if method == "hybrid" and active_user is None and not seed_title:
        st.info("No user and no seed movie — falling back to popularity (cold start).")

    render_cards(frame, data.movies, score_col, score_label, whys)

    with st.expander("Raw scores"):
        st.dataframe(frame, hide_index=True, width="stretch")


if __name__ == "__main__":
    main()
