"""
End-to-end pipeline
===================

    raw CSVs -> cleaning -> features -> analysis -> figures -> reports/findings.md

Run from the project root::

    python run_analysis.py            # thin shim -> this module
    python src/run_analysis.py        # identical

Every number that appears in ``reports/findings.md`` is interpolated from the
objects produced by this run - there are no hard-coded results anywhere, so
regenerating the dataset regenerates the write-up.
"""

from __future__ import annotations

import os
import sys
import time
from datetime import datetime

import numpy as np
import pandas as pd

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import config
    from analysis import fmt_p, run_all
    from cleaning import run_cleaning
    from features import build_all
    from visualize import make_all_figures
else:                                                        # pragma: no cover
    from . import config
    from .analysis import fmt_p, run_all
    from .cleaning import run_cleaning
    from .features import build_all
    from .visualize import make_all_figures


# ---------------------------------------------------------------------------
# markdown helpers (no tabulate dependency)
# ---------------------------------------------------------------------------
def md_table(df: pd.DataFrame, formatters: dict | None = None,
             headers: dict | None = None) -> str:
    formatters = formatters or {}
    headers = headers or {}
    cols = list(df.columns)
    head = "| " + " | ".join(headers.get(c, c) for c in cols) + " |"
    sep = "| " + " | ".join("---" for _ in cols) + " |"
    rows = []
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            f = formatters.get(c)
            if f is not None:
                cells.append(f(v))
            elif isinstance(v, (float, np.floating)):
                cells.append(f"{v:,.2f}")
            elif isinstance(v, (int, np.integer)):
                cells.append(f"{v:,}")
            else:
                cells.append(str(v))
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join([head, sep, *rows])


def gbp(v) -> str:
    return f"£{v:,.0f}"


def pct(v) -> str:
    return f"{v:.1%}"


def pct0(v) -> str:
    return f"{v:.0%}"


# ---------------------------------------------------------------------------
# findings.md
# ---------------------------------------------------------------------------
def write_findings(lines: pd.DataFrame, order_level: pd.DataFrame,
                   customer_level: pd.DataFrame, res: dict,
                   path: str | None = None) -> str:
    path = path or config.FINDINGS_REPORT
    g = res["growth"]
    par = res["pareto"]
    cat = res["categories"]
    reg = res["regions"]
    ch = res["channels"]
    co = res["cohorts"]
    rfm = res["rfm"]
    clv = res["clv"]
    churn = res["churn"]
    seas = res["seasonality"]
    t1, t2, t3 = res["tests"]

    # ---- derived numbers used in the executive summary -------------------
    top_cat = cat.iloc[0]
    best_margin_cat = cat.sort_values("margin_pct", ascending=False).iloc[0]
    worst_margin_cat = cat.sort_values("margin_pct").iloc[0]
    peak_share = (seas["by_month"].loc[seas["by_month"]["month"].isin([11, 12]),
                                       "avg_monthly_revenue"].sum()
                  / seas["by_month"]["avg_monthly_revenue"].sum())
    champs = rfm[rfm["rfm_segment"] == "Champions"]
    champ_cust_share = float(champs["customer_share"].iloc[0]) if len(champs) else np.nan
    champ_rev_share = float(champs["revenue_share"].iloc[0]) if len(champs) else np.nan
    dow = seas["by_dow"]
    weekend_share = float(dow.loc[dow["day_name"].isin(["Saturday", "Sunday"]), "revenue"].sum()
                          / dow["revenue"].sum())

    # recommendation sizing
    shift_pp = 0.05
    margin_gap = float(best_margin_cat["margin_pct"] - worst_margin_cat["margin_pct"])
    mix_shift_profit = shift_pp * g["total_net_revenue"] * margin_gap
    winback_rev = float(churn["high_value_at_risk_revenue"])
    winback_upside = 0.10 * winback_rev
    mobile_gap_orders = int(t1["n_mobile"])
    mobile_upside = mobile_gap_orders * t1["diff"] * 0.25 / 3      # per year, capture 25% of gap

    L: list[str] = []
    A = L.append

    A("# E-commerce Sales & Customer Behaviour - Findings\n")
    A(f"*Generated by `src/run_analysis.py` on {datetime.now():%Y-%m-%d %H:%M}. "
      f"All figures come from the run described in "
      f"[data_quality_report.md](data_quality_report.md).*\n")
    A(f"**Scope:** {len(lines):,} order lines, {order_level['order_id'].nunique():,} orders, "
      f"{customer_level['customer_id'].nunique():,} purchasing customers, "
      f"{lines['product_id'].nunique():,} SKUs, "
      f"{lines['order_date'].min():%b %Y} - {lines['order_date'].max():%b %Y}. "
      f"Net revenue {gbp(g['total_net_revenue'])}, gross profit "
      f"{gbp(g['total_gross_profit'])} ({pct(g['overall_margin_pct'])} margin).\n")

    # ======================================================================
    A("\n## Executive summary\n")
    A("### Five things the data says\n")
    A(f"1. **Revenue is growing fast but the growth is seasonal, not structural.** "
      f"Net revenue rose from {gbp(g['first_year_revenue'])} in {g['first_year']} to "
      f"{gbp(g['last_year_revenue'])} in {g['last_year']} "
      f"(+{pct0(g['growth_first_to_last'])}, {pct0(g['annualised_growth'])} a year). "
      f"But {pct0(peak_share)} of a typical year's revenue lands in November and December, "
      f"and January is the single worst month at "
      f"{pct0(seas['by_month'].loc[seas['by_month']['month'] == 1, 'index_vs_avg'].iloc[0] - 1)} "
      f"versus an average month. Peak trading month: {g['best_month']:%B %Y} at "
      f"{gbp(g['best_month_revenue'])}.\n")
    A(f"2. **The range is far more concentrated than 80/20 - it is closer to "
      f"{par['pct_products_for_80pct'] * 100:.0f}/80.** "
      f"{par['n_products_for_80pct']} of {par['n_products']} SKUs generate 80% of revenue; the "
      f"top 20% of the range generates {pct0(par['top20pct_revenue_share'])}. "
      f"The bottom half of the catalogue - {par['n_products'] - int(par['n_products'] * 0.5):,} "
      f"SKUs - contributes {pct(par['bottom50pct_revenue_share'])} of revenue while consuming the "
      f"same buying, warehousing and merchandising overhead.\n")
    A(f"3. **The biggest category is the least profitable one.** {top_cat['category']} is "
      f"{pct0(top_cat['revenue_share'])} of revenue but only {pct0(top_cat['profit_share'])} of "
      f"gross profit, at a {pct(top_cat['margin_pct'])} margin. "
      f"{best_margin_cat['category']} runs {pct(best_margin_cat['margin_pct'])} - a "
      f"{(best_margin_cat['margin_pct'] - worst_margin_cat['margin_pct']) * 100:.0f} "
      f"percentage-point spread that a one-way ANOVA confirms is real "
      f"(F = {t3['f_stat']:,.0f}, {fmt_p(t3['p_value'])}, "
      f"eta-squared = {t3['eta_squared']:.2f}).\n")
    A(f"4. **A fifth of customers carry half the business.** The {champs['customers'].iloc[0]:,} "
      f"RFM 'Champions' are {pct0(champ_cust_share)} of purchasing customers but "
      f"{pct0(champ_rev_share)} of revenue, and the top revenue decile alone accounts for "
      f"{pct0(clv['top_decile_revenue_share'])}. Mean estimated CLV is "
      f"{gbp(clv['mean_clv'])} against a median of {gbp(clv['median_clv'])} - "
      f"the average customer does not exist.\n")
    A(f"5. **Retention decays quickly and {pct0(churn['at_risk_rate'])} of the base is already "
      f"drifting away.** Only {pct0(co['m1_retention'])} of a cohort orders again in month 1 and "
      f"{pct0(co['m12_retention'])} are still active at month 12. "
      f"{churn['n_at_risk']:,} customers are past their own normal reorder window, representing "
      f"{gbp(churn['revenue_at_risk'])} of historic revenue "
      f"({pct0(churn['revenue_at_risk_share'])} of the total) and "
      f"{gbp(churn['clv_at_risk'])} of estimated forward value.\n")

    A("\n### Three recommendations\n")
    A(f"**R1. Cut the tail, protect the head.** Delist or consolidate the "
      f"{par['n_products'] - par['n_products_for_80pct']:,} SKUs outside the 80%-of-revenue core "
      f"and re-invest the freed working capital and shelf space in the "
      f"{par['n_products_for_80pct']} products that already work. Revenue at risk is bounded: the "
      f"bottom half of the range is only {pct(par['bottom50pct_revenue_share'])} of turnover, so "
      f"even losing all of it costs less than "
      f"{gbp(par['bottom50pct_revenue_share'] * g['total_net_revenue'] / 3)} a year, against a "
      f"far larger saving in complexity. Start with SKUs that are both bottom-quartile revenue "
      f"*and* below-median margin.\n")
    A(f"**R2. Rebalance the mix towards margin, not turnover.** {top_cat['category']} buys volume "
      f"at {pct(top_cat['margin_pct'])} while {best_margin_cat['category']} and "
      f"{cat.sort_values('margin_pct', ascending=False).iloc[1]['category']} sit above "
      f"{pct(cat.sort_values('margin_pct', ascending=False).iloc[1]['margin_pct'])}. "
      f"Shifting just 5 percentage points of revenue mix out of {worst_margin_cat['category']} "
      f"into {best_margin_cat['category']} is worth about {gbp(mix_shift_profit)} of extra gross "
      f"profit over a comparable three-year period ({gbp(mix_shift_profit / 3)} a year) at "
      f"identical turnover. Practical levers: category-weighted homepage and email real estate, "
      f"attach-rate bundles, and pulling discount funding out of "
      f"{worst_margin_cat['category']}, which already discounts at "
      f"{pct(float(cat.loc[cat['category'] == worst_margin_cat['category'], 'avg_discount'].iloc[0]))}.\n")
    A(f"**R3. Run a win-back programme against the {churn['high_value_at_risk']:,} lapsing "
      f"high-value customers before they are gone.** They are both in "
      f"the top two monetary quintiles and past their reorder window, carrying "
      f"{gbp(winback_rev)} of historic revenue. A win-back that recovers even 10% of them is "
      f"worth roughly {gbp(winback_upside)}, and the same customers are already identified in "
      f"`data/processed/customer_features.parquet` via `is_churn_risk` and `M`. "
      f"Pair it with a mobile attach-rate push: Mobile App orders average "
      f"{gbp(t1['mean_mobile'])} against {gbp(t1['mean_web'])} on Web "
      f"({fmt_p(t1['p_value'])}); closing a quarter of that gap on today's mobile volume is "
      f"about {gbp(mobile_upside)} a year.\n")

    # ======================================================================
    A("\n---\n\n## 1. Revenue trend and growth\n")
    A(f"![Revenue trend](figures/01_revenue_trend.png)\n")
    yearly = g["yearly_revenue"]
    ydf = pd.DataFrame({"year": yearly.index.astype(int), "net_revenue": yearly.to_numpy()})
    ydf["yoy"] = ydf["net_revenue"].pct_change()
    A(md_table(ydf, {"year": lambda v: f"{int(v)}", "net_revenue": gbp,
                     "yoy": lambda v: "-" if pd.isna(v) else pct(v)},
               {"year": "Year", "net_revenue": "Net revenue", "yoy": "YoY growth"}))
    A(f"\nThe linear trend adds {gbp(g['trend_slope_per_month'])} of revenue per month "
      f"(R2 = {g['trend_r2']:.2f}, {fmt_p(g['trend_p'])}), but the residual is dominated by "
      f"seasonality: mean month-on-month growth is {pct(g['mean_mom_growth'])} with a median of "
      f"{pct(g['median_mom_growth'])}, and the worst month "
      f"({g['worst_month']:%B %Y}, {gbp(g['worst_month_revenue'])}) is "
      f"{pct0(1 - g['worst_month_revenue'] / g['best_month_revenue'])} below the best.\n")
    A(f"\n![MoM growth](figures/02_mom_growth.png)\n")

    A("\n## 2. Seasonality and day-of-week\n")
    A(f"![Seasonality](figures/03_seasonality_heatmap.png)\n")
    bm = seas["by_month"][["month_name", "avg_monthly_revenue", "index_vs_avg"]]
    A(md_table(bm, {"avg_monthly_revenue": gbp, "index_vs_avg": lambda v: f"{v:.2f}x"},
               {"month_name": "Month", "avg_monthly_revenue": "Avg revenue / year",
                "index_vs_avg": "Index vs avg month"}))
    A(f"\nWeekends take {pct0(weekend_share)} of revenue from "
      f"{pct0(float(dow.loc[dow['day_name'].isin(['Saturday', 'Sunday']), 'orders'].sum() / dow['orders'].sum()))} "
      f"of orders - the weekend lift is footfall, not basket size (weekend AOV "
      f"{gbp(float(dow.loc[dow['day_name'].isin(['Saturday', 'Sunday']), 'aov'].mean()))} vs weekday "
      f"{gbp(float(dow.loc[~dow['day_name'].isin(['Saturday', 'Sunday']), 'aov'].mean()))}).\n")
    A(f"\n![Day of week](figures/04_day_of_week.png)\n")

    A("\n## 3. Products and the Pareto rule\n")
    A(f"![Pareto](figures/05_product_pareto.png)\n")
    top10 = res["products"].head(10)[["product_id", "name", "category", "net_revenue",
                                      "margin_pct", "units", "cum_revenue_share"]]
    A(md_table(top10, {"net_revenue": gbp, "margin_pct": pct,
                       "cum_revenue_share": pct, "units": lambda v: f"{v:,.0f}"},
               {"product_id": "SKU", "name": "Product", "category": "Category",
                "net_revenue": "Net revenue", "margin_pct": "Margin", "units": "Units",
                "cum_revenue_share": "Cumulative share"}))
    A(f"\nTop 10 SKUs alone are {pct(par['top10_revenue_share'])} of revenue.\n")

    A("\n## 4. Category economics\n")
    A(f"![Category margin](figures/06_category_margin_box.png)\n")
    A(md_table(cat[["category", "net_revenue", "revenue_share", "gross_profit",
                    "profit_share", "margin_pct", "avg_discount"]],
               {"net_revenue": gbp, "gross_profit": gbp, "revenue_share": pct,
                "profit_share": pct, "margin_pct": pct, "avg_discount": pct},
               {"category": "Category", "net_revenue": "Net revenue",
                "revenue_share": "Rev share", "gross_profit": "Gross profit",
                "profit_share": "Profit share", "margin_pct": "Margin",
                "avg_discount": "Avg discount"}))
    A(f"\n![Category revenue vs margin](figures/07_category_revenue_vs_margin.png)\n")

    A("\n## 5. Regional performance\n")
    A(f"![Regions](figures/08_regional_performance.png)\n")
    A(md_table(reg[["region", "net_revenue", "revenue_share", "orders", "aov", "customers",
                    "revenue_per_customer", "margin_pct", "shipping_pct_of_revenue"]],
               {"net_revenue": gbp, "revenue_share": pct, "aov": gbp,
                "revenue_per_customer": gbp, "margin_pct": pct,
                "shipping_pct_of_revenue": pct, "orders": lambda v: f"{v:,.0f}",
                "customers": lambda v: f"{v:,.0f}"},
               {"region": "Region", "net_revenue": "Net revenue", "revenue_share": "Share",
                "orders": "Orders", "aov": "AOV", "customers": "Customers",
                "revenue_per_customer": "Revenue / customer", "margin_pct": "Margin",
                "shipping_pct_of_revenue": "Shipping % of rev"}))

    A("\n## 6. Channel mix\n")
    A(f"![Channel mix](figures/09_channel_mix.png)\n")
    A(md_table(ch[["channel", "orders", "revenue_share", "aov", "median_aov", "avg_items",
                   "margin_pct", "avg_discount"]],
               {"revenue_share": pct, "aov": gbp, "median_aov": gbp, "margin_pct": pct,
                "avg_discount": pct, "orders": lambda v: f"{v:,.0f}",
                "avg_items": lambda v: f"{v:.2f}"},
               {"channel": "Channel", "orders": "Orders", "revenue_share": "Rev share",
                "aov": "AOV", "median_aov": "Median AOV", "avg_items": "Units / order",
                "margin_pct": "Margin", "avg_discount": "Avg discount"}))

    A("\n## 7. Cohort retention\n")
    A(f"![Cohort retention](figures/10_cohort_retention_heatmap.png)\n")
    curve = co["avg_curve"]
    cdf = pd.DataFrame({"month_since_first": curve.index.astype(int),
                        "retention": curve.to_numpy()})
    A(md_table(cdf.head(13), {"retention": pct},
               {"month_since_first": "Month since first order", "retention": "Active"}))
    A(f"\nAveraged over the {co['n_full_cohorts']} cohorts old enough to have a full 12-month "
      f"window. The curve flattens after month 3 - the customers who survive the first quarter "
      f"largely stay, so acquisition quality in month 0-3 is what determines lifetime value.\n")

    A("\n## 8. RFM segmentation\n")
    A(f"![RFM scatter](figures/11_rfm_scatter.png)\n")
    A(md_table(rfm[["rfm_segment", "customers", "customer_share", "total_revenue",
                    "revenue_share", "avg_order_value", "avg_frequency",
                    "avg_recency_days", "avg_clv", "churn_risk_rate"]],
               {"customer_share": pct, "total_revenue": gbp, "revenue_share": pct,
                "avg_order_value": gbp, "avg_clv": gbp, "churn_risk_rate": pct,
                "customers": lambda v: f"{v:,.0f}", "avg_frequency": lambda v: f"{v:.1f}",
                "avg_recency_days": lambda v: f"{v:,.0f}"},
               {"rfm_segment": "Segment", "customers": "Customers",
                "customer_share": "% of base", "total_revenue": "Revenue",
                "revenue_share": "% of revenue", "avg_order_value": "AOV",
                "avg_frequency": "Orders", "avg_recency_days": "Recency (d)",
                "avg_clv": "Avg CLV", "churn_risk_rate": "Churn risk"}))
    A(f"\n![RFM treemap](figures/12_rfm_treemap.png)\n")

    A("\n## 9. Customer lifetime value and churn risk\n")
    A(f"CLV is estimated as `margin per order x orders per year x expected remaining years`, "
      f"discounted at 10%. With an observed repeat rate of {pct(clv['repeat_rate'])}, the implied "
      f"expected life is {clv['expected_life_years']:.1f} years.\n")
    A(md_table(clv["clv_by_segment"],
               {"mean": gbp, "median": gbp, "sum": gbp, "count": lambda v: f"{v:,.0f}"},
               {"segment": "Customer segment", "count": "Customers", "mean": "Mean CLV",
                "median": "Median CLV", "sum": "Total CLV"}))
    A(f"\n**Churn risk.** A customer is flagged when their silence exceeds twice their own "
      f"average inter-purchase gap (floor 90 days), or 180 days for one-time buyers. "
      f"That flags {churn['n_at_risk']:,} customers ({pct(churn['at_risk_rate'])}), holding "
      f"{gbp(churn['revenue_at_risk'])} of historic revenue.\n")
    A(md_table(churn["by_segment"],
               {"revenue_at_risk": gbp, "at_risk_rate": pct,
                "customers": lambda v: f"{v:,.0f}", "at_risk": lambda v: f"{v:,.0f}"},
               {"rfm_segment": "Segment", "customers": "Customers", "at_risk": "At risk",
                "at_risk_rate": "Rate", "revenue_at_risk": "Revenue at risk"}))

    A("\n## 10. Average order value by customer segment\n")
    A(md_table(res["aov_segment"][["segment", "orders", "aov", "median_aov", "total",
                                   "revenue_share", "aov_index"]],
               {"aov": gbp, "median_aov": gbp, "total": gbp, "revenue_share": pct,
                "orders": lambda v: f"{v:,.0f}", "aov_index": lambda v: f"{v:.2f}x"},
               {"segment": "Segment", "orders": "Orders", "aov": "AOV",
                "median_aov": "Median AOV", "total": "Revenue",
                "revenue_share": "Share", "aov_index": "vs overall"}))

    # ======================================================================
    A("\n---\n\n## 11. Statistical tests\n")
    A("Each test states its assumptions, checks them, and reports a plain-English reading of "
      "the p-value alongside an effect size - a small p-value on 25,000 orders is easy to get "
      "and says nothing about whether the difference matters commercially.\n")
    for t in (t1, t2, t3):
        A(f"\n### {t['name']}\n")
        A(f"**Result:** {fmt_p(t['p_value'])} - "
          f"{'significant' if t['significant'] else 'not significant'} at alpha = {config.ALPHA:g}.\n")
        A(f"\n{t['interpretation']}\n")
    A("\n![Correlations](figures/13_correlation_matrix.png)\n")
    A("\n![Distributions](figures/14_distributions.png)\n")

    A("\n---\n\n## 12. Caveats\n")
    A("* The dataset is **synthetic**, produced by `data/generate_dataset.py` with a fixed seed. "
      "The behavioural structure (seasonality, retention decay, Pareto demand, category margins) "
      "is real in the sense that it was modelled deliberately - but no conclusion here describes "
      "an actual company.\n"
      "* CLV is a deterministic historic-average model, not a probabilistic one (BG/NBD + "
      "Gamma-Gamma would be the upgrade). It is fit for ranking customers, not for forecasting "
      "an individual's spend.\n"
      "* Cohort retention is measured on *orders*, so a customer who browses without buying "
      "counts as lapsed.\n"
      f"* {int(lines['is_price_outlier'].sum()):,} price outliers and "
      f"{int(lines['is_return'].sum()):,} returns are retained rather than dropped; every "
      "headline is therefore a net figure and reconciles to the source ledger.\n"
      "* Chi-square and ANOVA establish association, not causation; the regional segment mix "
      "could be driven by any number of unobserved confounders.\n")

    text = "\n".join(L)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text)
    return text


# ---------------------------------------------------------------------------
def main(make_figures: bool = True) -> dict:
    t0 = time.time()
    print("=" * 72)
    print("E-commerce sales & customer behaviour - full pipeline")
    print("=" * 72)

    if not os.path.exists(config.RAW_ORDERS):
        raise SystemExit(
            f"Raw data not found at {config.RAW_ORDERS}.\n"
            "Run `python data/generate_dataset.py` first."
        )

    config.ensure_dirs()
    orders, customers, products, _log = run_cleaning(write=True)
    lines, order_level, customer_level = build_all(orders, customers, products, write=True)
    res = run_all(lines, order_level, customer_level)
    if make_figures:
        make_all_figures(lines, order_level, customer_level, res)
    write_findings(lines, order_level, customer_level, res)

    print(f"[report] wrote {config.DATA_QUALITY_REPORT}")
    print(f"[report] wrote {config.FINDINGS_REPORT}")
    print(f"Done in {time.time() - t0:.1f}s")
    return {"lines": lines, "order_level": order_level,
            "customer_level": customer_level, "results": res}


if __name__ == "__main__":
    main()
